baseURL = "/"
languageCode = "en-us"
title = "Tech Blog"
theme = "piecodes"

# sectionPagesMenu = "main" # ---> Secondary option

Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number


[taxonomies]
  category = "categories"




[menu]

[[menu.main]]
    name       = "Home"
    identifier = "menu.home"
    url        = "/"
    weight     = 1

[[menu.main]]
    name       = "Blog"
    identifier = "menu.blog"
    url        = "/articles/"
    weight     = 2

[[menu.main]]
    name       = "Contact"
    identifier = "menu.contact"
    url        = "/contact/"
    weight     = 3
